#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $FSD_USER WITH PASSWORD '$FSD_PASSWORD';
	CREATE DATABASE $FSD_DB WITH OWNER $FSD_USER;
	GRANT ALL PRIVILEGES ON DATABASE $FSD_DB TO $FSD_USER;
EOSQL
